replace-key: abort if add-key was aborted

diff --git a/scripts/replace-key b/scripts/replace-key
--- a/scripts/replace-key
+++ b/scripts/replace-key
@@ -60,7 +60,10 @@ echo "Are you sure you want to update this key? (y/n)"
 read n
 
 if [ "x$n" = "xy" -o "x$n" = "xY" ]; then
-    $scriptdir/add-key $newkeytemp $keyring
+    if ! $scriptdir/add-key $newkeytemp $keyring ; then
+        echo "add-key failed"
+        exit 1
+    fi
 
     if [ "$keyring" = "debian-keyring-gpg" -o "$keyring" = "debian-nonupload-gpg" ]; then
 	name=`grep $newkey keyids | sed 's/^[^ ]* //'|sed s/\<.*//`
